commands:
  build_command:
    description: "Build and Test SingularityNET Services"
    parameters:
      docker_nvidia:
        type: boolean
        default: false
      docker_image_name:
        type: string
        default: ""
      docker_container_name:
        type: string
        default: ""
      docker_mount_volumes:
        type: boolean
        default: false
      docker_mount_src:
        type: string
        default: ""
      docker_mount_dest:
        type: string
        default: ""
    steps:
      - run:
          name: Building
          command: |
            echo "==================================================== Build Configs ==================================================="
            export DOCKER_NVIDIA=<< parameters.docker_nvidia >>
            export DOCKER_IMAGE_NAME=<< parameters.docker_image_name >>
            export DOCKER_CONTAINER_NAME=<< parameters.docker_container_name >>
            export DOCKER_MOUNT_VOLUMES=<< parameters.docker_mount_volumes >>
            export DOCKER_MOUNT_SRC=<< parameters.docker_mount_src >>
            export DOCKER_MOUNT_DEST=<< parameters.docker_mount_dest >>
            echo            git_user  : ${CIRCLE_PROJECT_USERNAME}
            echo            git_repo  : ${CIRCLE_PROJECT_REPONAME}
            echo            git_branch: ${CIRCLE_BRANCH}
            echo SSH_USER             : ${SSH_USER}
            echo SSH_HOST             : ${SSH_HOST}
            echo DOCKER_NVIDIA        : ${DOCKER_NVIDIA}
            echo DOCKER_IMAGE_NAME    : ${DOCKER_IMAGE_NAME}
            echo DOCKER_CONTAINER_NAME: ${DOCKER_CONTAINER_NAME}
            echo DOCKER_MOUNT_VOLUMES : ${DOCKER_MOUNT_VOLUMES}
            echo DOCKER_MOUNT_SRC     : ${DOCKER_MOUNT_SRC}
            echo DOCKER_MOUNT_DEST    : ${DOCKER_MOUNT_DEST}
            echo "======================================================================================================================"

            ssh -o "StrictHostKeyChecking no" ${SSH_USER}@${SSH_HOST} \<< EOF
              docker stop ${DOCKER_CONTAINER_NAME} || true && docker rename ${DOCKER_CONTAINER_NAME} ${DOCKER_CONTAINER_NAME}_old || true
              docker build \
                --build-arg git_owner=${CIRCLE_PROJECT_USERNAME} \
                --build-arg git_repo=${CIRCLE_PROJECT_REPONAME} \
                --build-arg git_branch=${CIRCLE_BRANCH} \
                -t ${DOCKER_IMAGE_NAME}:${CIRCLE_PROJECT_USERNAME} https://raw.githubusercontent.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/${CIRCLE_BRANCH}/${SERVICE_FOLDER}/Dockerfile
              docker run \
                $([ "${DOCKER_NVIDIA}" = "true" ] && echo "--runtime=nvidia" || echo "") \
                --name ${DOCKER_CONTAINER_NAME} \
                $([ "${DOCKER_MOUNT_VOLUMES}" = "true" ] && echo "-v ${DOCKER_MOUNT_SRC}:${DOCKER_MOUNT_DEST}" || echo "") \
                -di ${DOCKER_IMAGE_NAME}:${CIRCLE_PROJECT_USERNAME} ${SERVICE_RUN_COMMAND}
            EOF
      - run:
          name: Removing old Docker Container
          command: |
            export DOCKER_IMAGE_NAME=<< parameters.docker_image_name >>
            export DOCKER_CONTAINER_NAME=<< parameters.docker_container_name >>

            ssh -o "StrictHostKeyChecking no" ${SSH_USER}@${SSH_HOST} \<< EOF
              docker stop ${DOCKER_CONTAINER_NAME}_old || true && docker rm ${DOCKER_CONTAINER_NAME}_old || true
            EOF
      - run:
          name: Testing local
          command: |
            export DOCKER_IMAGE_NAME=<< parameters.docker_image_name >>
            export DOCKER_CONTAINER_NAME=<< parameters.docker_container_name >>

            ssh -o "StrictHostKeyChecking no" ${SSH_USER}@${SSH_HOST} \<< EOF
              docker exec -i ${DOCKER_CONTAINER_NAME} ${SERVICE_TEST_COMMAND}
            EOF

  deploy_command:
    description: "Deploy SingularityNET Services"
    parameters:
      docker_nvidia:
        type: boolean
        default: false
      docker_image_name:
        type: string
        default: ""
      docker_container_name:
        type: string
        default: ""
      docker_etcd_host_folder:
        type: string
        default: ""
      docker_etcd_container_folder:
        type: string
        default: ""
      docker_mount_volumes:
        type: boolean
        default: false
      docker_mount_src:
        type: string
        default: ""
      docker_mount_dest:
        type: string
        default: ""
    steps:
      - run:
          name: Deploying
          command: |
            echo "=================================================== Deploy Configs ==================================================="
            export DOCKER_DEPLOY=$([ "${CIRCLE_PROJECT_USERNAME}" = "singnet" ] && echo "true" || echo "false")
            export DOCKER_NVIDIA=<< parameters.docker_nvidia >>
            export DOCKER_IMAGE_NAME=<< parameters.docker_image_name >>
            export DOCKER_CONTAINER_NAME=<< parameters.docker_container_name >>
            export DOCKER_MOUNT_VOLUMES=<< parameters.docker_mount_volumes >>
            export DOCKER_MOUNT_SRC=<< parameters.docker_mount_src >>
            export DOCKER_MOUNT_DEST=<< parameters.docker_mount_dest >>
            export ETCD_HOST_FOLDER=<< parameters.docker_etcd_host_folder >>
            export ETCD_CONTAINER_FOLDER=<< parameters.docker_etcd_container_folder >>
            echo            git_user  : ${CIRCLE_PROJECT_USERNAME}
            echo            git_repo  : ${CIRCLE_PROJECT_REPONAME}
            echo            git_branch: ${CIRCLE_BRANCH}
            echo SSH_USER             : ${SSH_USER}
            echo SSH_HOST             : ${SSH_HOST}
            echo DOCKER_DEPLOY        : ${DOCKER_DEPLOY}
            echo DOCKER_NVIDIA        : ${DOCKER_NVIDIA}
            echo DOCKER_IMAGE_NAME    : ${DOCKER_IMAGE_NAME}
            echo DOCKER_CONTAINER_NAME: ${DOCKER_CONTAINER_NAME}
            echo DOCKER_MOUNT_VOLUMES : ${DOCKER_MOUNT_VOLUMES}
            echo DOCKER_MOUNT_SRC     : ${DOCKER_MOUNT_SRC}
            echo DOCKER_MOUNT_DEST    : ${DOCKER_MOUNT_DEST}
            echo ETCD_HOST_FOLDER     : ${ETCD_HOST_FOLDER}
            echo ETCD_CONTAINER_FOLDER: ${ETCD_CONTAINER_FOLDER}
            echo "======================================================================================================================"

            if [ "$DOCKER_DEPLOY" = "true" ]; then
            	echo "Status: Deploying..."
            	ssh -o "StrictHostKeyChecking no" ${SSH_USER}@${SSH_HOST} \<<-EOF
                    docker stop PROD_${DOCKER_CONTAINER_NAME} || true && docker rename PROD_${DOCKER_CONTAINER_NAME} PROD_${DOCKER_CONTAINER_NAME}_old || true
                    docker build \
                    --build-arg git_owner=${CIRCLE_PROJECT_USERNAME} \
                    --build-arg git_repo=${CIRCLE_PROJECT_REPONAME} \
                    --build-arg git_branch=${CIRCLE_BRANCH} \
                    -t ${DOCKER_IMAGE_NAME}:${CIRCLE_PROJECT_USERNAME} https://raw.githubusercontent.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/${CIRCLE_BRANCH}/${SERVICE_FOLDER}/Dockerfile
                    docker run \
                    $([ "${DOCKER_NVIDIA}" = "true" ] && echo "--runtime=nvidia" || echo "") \
                    --name PROD_${DOCKER_CONTAINER_NAME} \
                    --restart unless-stopped \
                    $([ "${DOCKER_DEPLOY}" = "true" ] && echo "-p ${SNETD_PORT_KOVAN}:${SNETD_PORT_KOVAN}" || echo "") \
                    $([ "${DOCKER_DEPLOY}" = "true" ] && echo "-p ${SNETD_PORT_ROPSTEN}:${SNETD_PORT_ROPSTEN}" || echo "") \
                    $([ "${DOCKER_DEPLOY}" = "true" ] && echo "-v ~/${ETCD_HOST_FOLDER}:/${ETCD_CONTAINER_FOLDER}" || echo "") \
                    $([ "${DOCKER_MOUNT_VOLUMES}" = "true" ] && echo "-v ${DOCKER_MOUNT_SRC}:${DOCKER_MOUNT_DEST}" || echo "") \
                    -di ${DOCKER_IMAGE_NAME}:${CIRCLE_PROJECT_USERNAME} ${SERVICE_RUN_COMMAND}
            	EOF
            else
            	echo "Status: Not deploying..."
            fi

      - run:
          name: Removing old Docker Container
          command: |
            export DOCKER_DEPLOY=$([ "${CIRCLE_PROJECT_USERNAME}" = "singnet" ] && echo "true" || echo "false")
            if [ "$DOCKER_DEPLOY" = "true" ]; then
            	echo "Status: Deploying..."
            	export DOCKER_IMAGE_NAME=<< parameters.docker_image_name >>
            	export DOCKER_CONTAINER_NAME=<< parameters.docker_container_name >>
            	ssh -o "StrictHostKeyChecking no" ${SSH_USER}@${SSH_HOST} \<<-EOF
                    docker stop PROD_${DOCKER_CONTAINER_NAME}_old || true && docker rm PROD_${DOCKER_CONTAINER_NAME}_old || true
            	EOF
            else
            	echo "Status: Not deploying..."
            fi

      - run:
          name: Testing local
          command: |
            export DOCKER_DEPLOY=$([ "${CIRCLE_PROJECT_USERNAME}" = "singnet" ] && echo "true" || echo "false")
            if [ "$DOCKER_DEPLOY" = "true" ]; then
            	echo "Status: Deploying..."
            	export DOCKER_IMAGE_NAME=<< parameters.docker_image_name >>
            	export DOCKER_CONTAINER_NAME=<< parameters.docker_container_name >>
            	ssh -o "StrictHostKeyChecking no" ${SSH_USER}@${SSH_HOST} \<<-EOF
                    docker exec -i PROD_${DOCKER_CONTAINER_NAME} ${SERVICE_TEST_COMMAND}
            	EOF
            else
            	echo "Status: Not deploying..."
            fi

version: 2.1
jobs:
  build-cntk-next-day-trend:
    docker:
    - image: circleci/python:3.6.6-node
    working_directory: ~/singnet
    environment:
      SERVICE_NAME: cntk-next-day-trend
      SERVICE_FOLDER: finance/cntk-next-day-trend
      SERVICE_RUN_COMMAND: bash -c "source '/cntk/activate-cntk';python3 run_next_day_trend_service.py"
      SERVICE_TEST_COMMAND: bash -c "source '/cntk/activate-cntk';python3 test_next_day_trend_service.py auto"
    steps:
      - build_command:
          docker_nvidia: true
          docker_image_name: cntk_next_day_trend
          docker_container_name: CNTK_NEXT_DAY_TREND

  deploy-cntk-next-day-trend:
    docker:
    - image: circleci/python:3.6.6-node
    working_directory: ~/singnet
    environment:
      SERVICE_NAME: cntk-next-day-trend
      SERVICE_FOLDER: finance/cntk-next-day-trend
      SERVICE_RUN_COMMAND: bash -c "source '/cntk/activate-cntk';python3 run_next_day_trend_service.py"
      SERVICE_TEST_COMMAND: bash -c "source '/cntk/activate-cntk';python3 test_next_day_trend_service.py auto"
      SNETD_PORT_KOVAN: 7001
      SNETD_PORT_ROPSTEN: 7051
    steps:
      - deploy_command:
          docker_nvidia: true
          docker_image_name: cntk_next_day_trend
          docker_container_name: CNTK_NEXT_DAY_TREND
          docker_etcd_host_folder: singnet/etcd/${SERVICE_NAME}/
          docker_etcd_container_folder: opt/singnet/${CIRCLE_PROJECT_REPONAME}/${SERVICE_FOLDER}/etcd/

  build-cntk-lstm-forecast:
    docker:
      - image: circleci/python:3.6.6-node
    working_directory: ~/singnet
    environment:
      SERVICE_NAME: cntk-lstm-forecast
      SERVICE_FOLDER: generic/cntk-lstm-forecast
      SERVICE_RUN_COMMAND: bash -c "source '/cntk/activate-cntk';python3 run_time_series_forecast_service.py"
      SERVICE_TEST_COMMAND: bash -c "source '/cntk/activate-cntk';python3 test_time_series_forecast_service.py auto"
    steps:
      - build_command:
          docker_nvidia: true
          docker_image_name: cntk_lstm_forecast
          docker_container_name: CNTK_LSTM_FORECAST

  deploy-cntk-lstm-forecast:
    docker:
    - image: circleci/python:3.6.6-node
    working_directory: ~/singnet
    environment:
      SERVICE_NAME: cntk-lstm-forecast
      SERVICE_FOLDER: generic/cntk-lstm-forecast
      SERVICE_RUN_COMMAND: bash -c "source '/cntk/activate-cntk';python3 run_time_series_forecast_service.py"
      SERVICE_TEST_COMMAND: bash -c "source '/cntk/activate-cntk';python3 test_time_series_forecast_service.py auto"
      SNETD_PORT_KOVAN: 7009
      SNETD_PORT_ROPSTEN: 7059
    steps:
      - deploy_command:
          docker_nvidia: true
          docker_image_name: cntk_lstm_forecast
          docker_container_name: CNTK_LSTM_FORECAST
          docker_etcd_host_folder: singnet/etcd/${SERVICE_NAME}/
          docker_etcd_container_folder: opt/singnet/${CIRCLE_PROJECT_REPONAME}/${SERVICE_FOLDER}/etcd/

workflows:
  version: 2.1
  build_deploy_time_series_services:
    jobs:
      - build-cntk-next-day-trend
      - deploy-cntk-next-day-trend:
          requires:
            - build-cntk-next-day-trend
          filters:
            branches:
              only: master

      - build-cntk-lstm-forecast
      - deploy-cntk-lstm-forecast:
          requires:
            - build-cntk-lstm-forecast
          filters:
            branches:
              only: master