version: 2.1

orbs:
  ssh-deployment: singularitynet/ssh-deployment@1.1.5

jobs:
  cntk-next-day-trend:
    docker:
      - image: circleci/python:3.6.6-node
    steps:
      - checkout
      - ssh-deployment/deploy:
          ssh-host: ${SSH_HOST}
          ssh-user: ${SSH_USER}
          service-dir: "finance/cntk-next-day-trend"
          mainnet-port: "7001"
          testnet-port: "7051"
          run-command: "source '/cntk/activate-cntk';python3 run_next_day_trend_service.py --ssl --metering"
          test-command: "sleep 20;source '/cntk/activate-cntk';python3 test_next_day_trend_service.py auto"
          docker-test-files: "Dockerfile, requirements.txt"
          docker-file-path: "finance/cntk-next-day-trend/Dockerfile"
          docker-no-cache: true
          docker-image: "cntk_next_day_trend"
          docker-container: "CNTK_NEXT_DAY_TREND"
          docker-nvidia: true
          docker-volumes: "-v ~/singnet/.certs:/opt/singnet/.certs"
          infura-api-key: ${INFURA_API_KEY}
          daemon-version: ${CI_SNETD_VERSION}
          daemon-pk: ${PK_CNTK_NEXT_DAY_TREND}
  cntk-lstm-forecast:
    docker:
      - image: circleci/python:3.6.6-node
    steps:
      - checkout
      - ssh-deployment/deploy:
          ssh-host: ${SSH_HOST}
          ssh-user: ${SSH_USER}
          service-dir: "finance/cntk-lstm-forecast"
          mainnet-port: "7009"
          testnet-port: "7059"
          run-command: "source '/cntk/activate-cntk';python3 run_time_series_forecast_service.py --ssl --metering"
          test-command: "sleep 20;source '/cntk/activate-cntk';python3 test_time_series_forecast_service.py auto"
          docker-test-files: "Dockerfile, requirements.txt"
          docker-file-path: "generic/cntk-lstm-forecast/Dockerfile"
          docker-no-cache: true
          docker-image: "cntk_lstm_forecast"
          docker-container: "CNTK_LSTM_FORECAST"
          docker-nvidia: true
          docker-volumes: "-v ~/singnet/.certs:/opt/singnet/.certs"
          infura-api-key: ${INFURA_API_KEY}
          daemon-version: ${CI_SNETD_VERSION}
          daemon-pk: ${PK_CNTK_LSTM_FORECAST}

workflows:
  build_deploy_ts_services:
    jobs:
      - cntk-next-day-trend
      - cntk-lstm-forecast